theme: jekyll-theme-minimal
title: Моя сторінка
description: Моя персональна сторінка
author: Pavlo Shcherbukha
github: https://github.com/pavlo-shcherbukha
about: Зараз програмую на  Node.js та VUE
logo: /assets/img/robot-1.jpg

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/pavlo-shcherbukha"
urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

