theme: jekyll-theme-minimal
title: Павло Щербуха
description: Персональна освітня сорінка
author: Pavlo Shcherbukha
github: https://github.com/pavlo-shcherbukha
about: Розробка на Node.js, VUE.js, Python, IBM Integration Bus (App Connect Ent) , ORACLE PL/SQL
logo: /assets/img/pasha.jpg
markdown: kramdown

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/pavel-shcherbukha-a788a26a/"
    - icon: fa-github
      link: "https://github.com/pavlo-shcherbukha"
urls:
    - text: Про себе
      url: /about/
    - text: Проекти
      url: /projects/
    - text: Корисні лінки
      url: /uflinks/

